---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mule-pv
  namespace: mule
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/joseph/projects/mule-system2/mule/storage/vfs"