---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rethinkdb-pv
  namespace: mule
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/joseph/projects/mule-system2/docker/rethinkdb/data"