#
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rethinkdb-pvc
  namespace: mule
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi